# -*- coding: utf-8 -*-
"""function_calling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiSuIWpc0aV6d4Joh21Dvu8Rk2QJsmCR
"""

from huggingface_hub import hf_hub_download

model_path = hf_hub_download(
    repo_id="Qwen/Qwen3-14B-GGUF",
    filename="Qwen3-14B-Q4_K_M.gguf"
)

!pip install llama-cpp-python

from llama_cpp import Llama

llm = Llama(
    model_path=model_path,
    n_ctx=8192,
    n_gpu_layers=-1,  # use GPU
    verbose=False
)

def get_current_time(location):
    from datetime import datetime

    return {
        "location": location,
        "time": "13:47:30"
    }
def get_weather(location):
    return {
        "location": location,
        "temperature": "30°C"
    }

available_functions = {
    "get_current_time": get_current_time,
    "get_weather": get_weather
}

tools = [
    {
        "type": "function",
        "function": {
            "name": "get_current_time",
            "description": "Get current time of a city",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "Location name"
                    }
                },
                "required": ["location"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_weather",
            "description": "Get weather of a city",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "Location"
                    }
                },
                "required": ["location"]
            }
        }
    }
]

messages = [
    {
        "role": "user",
        "content": "What's the weather and time in Kochi?"
    }
]

import json

while True:

    response = llm.create_chat_completion(
        messages=messages,
        tools=tools,
        tool_choice="auto"
    )

    message = response["choices"][0]["message"]

    # If no tool call -> final answer
    if message.get("tool_calls") is None:
        print("\nFINAL ANSWER:")
        print(message["content"])
        break

    messages.append(message)

    # Execute all tool calls
    for tool_call in message["tool_calls"]:

        function_name = tool_call["function"]["name"]

        arguments = json.loads(
            tool_call["function"]["arguments"]
        )

        print(f"\nCalling: {function_name}")
        print("Arguments:", arguments)

        function = available_functions[function_name]

        result = function(**arguments)

        print("Result:", result)

        messages.append({
            "role": "tool",
            "tool_call_id": tool_call["id"],
            "name": function_name,
            "content": json.dumps(result)
        })

import re
import json

content = response["choices"][0]["message"]["content"]

tool_calls = re.findall(
    r"<tool_call>\s*(.*?)\s*</tool_call>",
    content,
    re.DOTALL
)

for call in tool_calls:
    tool_data = json.loads(call)

    print(tool_data)

available_functions = {
    "get_weather": get_weather,
    "get_current_time": get_current_time
}

tool_results = []

for call in tool_calls:
    tool_data = json.loads(call)

    fn_name = tool_data["name"]
    args = tool_data["arguments"]

    result = available_functions[fn_name](**args)

    tool_results.append({
        "name": fn_name,
        "result": result
    })

messages.append({
    "role": "assistant",
    "content": content
})

messages.append({
    "role": "user",
    "content": f"Tool results: {json.dumps(tool_results)}"
})

final_response = llm.create_chat_completion(
    messages=messages
)

print(final_response["choices"][0]["message"]["content"])